### ISSUE TITLE
[BUG] Player texture enchanted pixels also appear emissive

### ISSUE THREAD

**Issue by Thanos1716** [Traben-0/Entity_Texture_Features#108] opened 2022-10-11 16:15 UTC
On viewing any player model with enchanted pixels enabled, but irrelevant of whether emissive pixels are enabled or disabled, in darkness the enchanted pixels appear emissive, I believe this is a consequence of applying the emissiveness to both the main texture and the enchantment texture, as naturally the enchantment texture should appear emissive, but the main texture should not

I would consider this a bug because it does not match vanilla enchantment texture behaviour
If you use the vanilla enchantment glint this is not very clear, but with most resourcepacks to change it, the effect becomes quite noticeable

![2022-10-11_17 09 54](https://user-images.githubusercontent.com/80975570/195144440-ed6ae60c-5820-47c8-840d-2650d47c2fa8.png)

![2022-10-11_16 59 36](https://user-images.githubusercontent.com/80975570/195144406-62383e2c-9af7-4f8a-8fd8-311da1bb529d.png)

- Minecraft version: 1.19.2
- Launcher: PolyMC
- ModLoader: fabric
- ETF Version: 4.1.1
- Does the issue persist with only ETF (and cloth config for forge versions) installed?: Yes
 
(also the whole outside the default UVs idea is epic :D)

**Comment by Traben-0** [comment] 2022-10-14 07:38
I know the cause i'll look into it

**Comment by Traben-0** [comment] 2022-11-16 06:38
fixed in release 4.2

**Closed by Traben-0** 2022-11-16 06:38 UTC
Labels: bug, Fixed or added in dev build (released)
