### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Heartveiler** [Traben-0/Entity_Texture_Features#98] opened 2022-08-15 04:39 UTC
https://bytebin.lucko.me/a9IvZMF1pj

**Comment by Traben-0** [comment] 2022-08-15 06:46
duplicate of #93  there is a dev build on my discord that will release soon with a fix for this crash

**Comment by Traben-0** [comment] 2022-08-15 06:46
you can find it on my discord already in the #devlog channel
it is versio 4.0.2.beta.3

**Closed by Traben-0** 2022-08-15 06:46 UTC

**Comment by Heartveiler** [comment] 2022-08-21 10:41
thank u
