### ISSUE TITLE
Forge 1.18.2 Client crash

### ISSUE THREAD

**Issue by raffle2** [Traben-0/Entity_Texture_Features#80] opened 2022-06-29 20:22 UTC
Hey, thank you for the mod, just jumped out of optifine and was looking for something like this, it seems I can't run it though, I don't know exactly what's causing the crash except it's something to do with elytra, here's the crash report:
https://pastebin.com/7b4ktjkz
I know I'm using 3.1.3 in this case but I used 3.1.4 before and had the same issue (just went back a version to see if it helped)

Thanks for reading 👍

**Comment by Traben-0** [comment] 2022-06-30 05:41
strange, try and delete your .minecraft/configs/entity_texture_features.json  file see if that fixes it

if it doesn't I have a dev build on my discord that might fix this https://discord.com/invite/rURmwrzUcz

**Comment by Traben-0** [comment] 2022-06-30 12:22
duplicate of #78

**Closed by Traben-0** 2022-06-30 12:22 UTC

**Comment by Traben-0** [comment] 2022-07-01 01:56
Sorry that build will be up later tonight actually

**Comment by Traben-0** [comment] 2022-07-01 11:49
fix is up for version 3.1.5 for forge
