### ISSUE TITLE
[BUG] Crash when open inventory

### ISSUE THREAD

**Issue by ClockworkzAI** [Traben-0/Entity_Texture_Features#123] opened 2022-11-17 23:33 UTC
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-log channel*

**Describe the issue**

I open my inventory and the game started to crash

**Screenshots**

Sorry Cant get any

**Crash log**
[crash-2022-11-18_01.15.56-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/10036454/crash-2022-11-18_01.15.56-client.txt)

**Your setup: (please complete the following information):**

- Minecraft version: 1.18.2
- ModLoader: forge
- ETF Version: 4.2.0
- Does the issue persist with only ETF (and cloth config for forge versions) installed? Don't know so far but I only updated this mod, will come back as soon as possible

**Comment by Traben-0** [comment] 2022-11-17 23:36
Disabling block entity features should prevent this crash,  I will look further into the cause

**Comment by Traben-0** [comment] 2022-11-17 23:37
Do let me know if it persists with only etf installed

**Comment by Traben-0** [comment] 2022-11-18 09:09
I cannot replicate this myself

can you ensure you have the latest forge version for 1.18.2 and can you check if it still crashes with only ETF installed.
I'm thinking it could be a compatibility issue with one of your mods

**Comment by ClockworkzAI** [comment] 2022-11-18 11:03
It works with 4.1.1
I have 231 mods installed thinking  it is the shaders ocolos mod issue
Will check

**Comment by ClockworkzAI** [comment] 2022-11-18 16:23
Or tinker regforged

**Comment by ClockworkzAI** [comment] 2022-11-19 12:41
> Disabling block entity features should prevent this crash, I will look further into the cause

no didn't work

**Comment by Traben-0** [comment] 2022-11-19 12:42
Hmm, did you narrow down what mods were conflicting?

**Comment by ClockworkzAI** [comment] 2022-11-19 13:17
yes and it is:
		TConstruct-1.18.2-3.5.2.40.jar                    |Tinkers' Construct            |tconstruct                    |3.5.2.40            |DONE      |Manifest: NOSIGNATURE
		entity_texture_features_forge_1.18.2-4.2.0.jar    |Entity Texture Features       |entity_texture_features       |4.2.0               |DONE      |Manifest: NOSIGNATURE
		TCIntegrations-1.18.2-2.0.15.0.jar                |Tinkers' Integrations and Twea|tcintegrations                |1.18.2-2.0.15.0     |DONE      |Manifest: da:bf:8b:25:96:f3:b9:28:12:15:50:54:25:99:97:10:61:cf:4e:63:30:09:40:fb:93:39:1d:7e:6b:93:9b:17
		forge-1.18.2-40.1.84-universal.jar                |Forge                         |forge                         |40.1.84             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |DONE      |Manifest: NOSIGNATURE
		Tinkers Reforged 1.18.2-1.1.4.jar                 |Tinkers Reforged              |tinkers_reforged              |1.1.4               |DONE      |Manifest: NOSIGNATURE
		tinker_rapier-1.1.4-1.18.2.jar                    |Tinkers' Rapier               |tinker_rapier                 |1.1.4-1.18.2        |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.31.jar                          |Mantle                        |mantle                        |1.9.31              |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.18.2-1.2.5a.jar                        |Oculus                        |oculus                        |1.2.5a              |DONE      |Manifest: NOSIGNATURE

**Comment by ClockworkzAI** [comment] 2022-11-19 13:28
I feel like some of the tinker mods cant see the texture.

**Comment by Traben-0** [comment] 2022-11-19 13:29
I'll have a close look at these mods and see what the issue is, when I get time

**Comment by ClockworkzAI** [comment] 2022-11-19 13:39
[crash-2022-11-19_15.07.30-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/10047108/crash-2022-11-19_15.07.30-client.txt)
I tested with just tinkers and Entity texture features I got this crash.

**Comment by Traben-0** [comment] 2022-11-20 00:23
I will see what i can do

**Comment by Traben-0** [comment] 2022-12-31 12:54
this has been resolved in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0

**Closed by Traben-0** 2022-12-31 12:54 UTC
Labels: bug, mod compatability, Fixed or added in dev build (released)
