### ISSUE TITLE
[Quark mod] incompatible with block entity features

### ISSUE THREAD

**Issue by Akaixz** [Traben-0/Entity_Texture_Features#83] opened 2022-07-12 21:58 UTC
I'm having a problem with this mod + quark mod, i already write a issue to vazkii (quark developer), i'm playing on 1.18.2, i've tested both mods alone and it still crashes, here's what quark developer said: 
https://github.com/VazkiiMods/Quark/issues/3817#event-6965951112

Version: 1.18.2
Forgeloader: 40.1.54

How to reproduce:
1.  Install this mod
2.  Install Quark
3.  Click on quark "q" button

Logs: 
- Crash Log: https://pastebin.com/0ZJ1uSJv
- Latest Log: https://pastebin.com/W6ChKfVa

**Comment by Traben-0** [comment] 2022-07-26 01:56
in random texture settings you can disable block entity features, you might have to do this for the time being. behind the scenes ETF uses an armour stand as a stand-in for block entities when using those features, quarks armorstand features conflict with this somehow so until i figure a workaround disable all block entity features in ETF's settings

**Comment by Traben-0** [comment] 2022-07-26 03:00
i have added a check to disable the offending feature if quark is detected, i will leave the issue open for now as this is only a half solution

**Comment by Akaixz** [comment] 2022-08-14 21:56
Thanks for your help, it works now, hope you can fix this!

**Comment by Traben-0** [comment] 2022-11-06 07:06
fixed the underlying cause in dev build 4.1.1.dev.3 

issue will remain open until the fix is in a stable release

**Comment by Traben-0** [comment] 2022-11-16 06:38
root cause fixed in release 4.2

**Closed by Traben-0** 2022-11-16 06:38 UTC
Labels: mod compatability, Fixed or added in dev build (released)
