### ISSUE TITLE
Renamed villager behavior

### ISSUE THREAD

**Issue by SebSemos** [Traben-0/Entity_Texture_Features#126] opened 2022-11-27 23:39 UTC
Hi. When I rename a villager to get a custom texture it works instantly with their base textures (villager.png)
But when I do it in their "type" subfolder I need a reload of ressource packs or logon/off the world for it to be effective.

- Minecraft version: [ 1.19.2]
- ModLoader: fabric]
- ETF Version [e.g. 4.2.0]
- Does the issue persist with only ETF installed? Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? Yep, close case but seemed to be fine from what I read

**Comment by Traben-0** [comment] 2022-11-28 01:55
I know the cause I will have it fixed next version

**Comment by Traben-0** [comment] 2022-12-31 12:54
this has been resolved in release 4.3 https://github.com/Traben-0/Entity_Texture_Features/releases/tag/v4.3.0

**Closed by Traben-0** 2022-12-31 12:54 UTC
Labels: bug, Fixed or added in dev build (released)
