### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by knoxhack** [Traben-0/Entity_Texture_Features#204] opened 2023-10-01 06:20 UTC
**Crash log**
[crash-2023-09-29_00.58.17-client.txt](https://github.com/Traben-0/Entity_Texture_Features/files/12776519/crash-2023-09-29_00.58.17-client.txt).

- Minecraft version: 1.20.1
- ModLoader: Forge
- ETF Version: entity_texture_features_forge_1.20-4.5.1

**Comment by Traben-0** [comment] 2023-10-01 06:21
This is known I am working on it

**Comment by knoxhack** [comment] 2023-10-01 17:23
awesome, thanks :)

**Comment by merasmus44** [comment] 2023-10-18 12:22
was this ever fixed? because i'm having the exact same issue

**Comment by Traben-0** [comment] 2023-10-18 12:24
It is technically already fixed on the 1.20.2 dev branch I'll have dev builds up soon in my discord

**Comment by merasmus44** [comment] 2023-10-18 12:25
will it work on 1.20.1?

**Comment by Traben-0** [comment] 2023-10-18 12:25
I fixed this and and all future similar Issues by rewriting a major part of the texture property code, so I've needed to make sure its stable

**Comment by Traben-0** [comment] 2023-10-18 12:28
> will it work on 1.20.1?

I will release it for 1.20.1 yes,  but that branch's build won't work for it if you build it

**Comment by Ghost-chu** [comment] 2023-10-20 10:45
> > will it work on 1.20.1?
> 
> I will release it for 1.20.1 yes, but that branch's build won't work for it if you build it

Can also reproduce on 1.20.2 version.

**Comment by Traben-0** [comment] 2023-10-21 06:06
this should be fixed in the 4.6 dev build on my discord, only released for 1.20.2 for the moment

**Closed** 2023-12-29 07:48 UTC
Labels: bug, Fixed or added in dev build (released), Fixed or added in dev build (un-released)
